name: 米游社每日签到

on:
  schedule:
    # UTC 时间 每天 01:00 = 北京时间 每天 09:00
    # 北京时间 = UTC + 8小时，按需自行修改
    - cron: '30 21 * * *'
  # 开启手动触发按钮，方便测试
   workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖库
        run: pip install -r requirements.txt

      - name: 生成配置文件
        env:
          CONFIG_CONTENT: ${{ secrets.CONFIG_YAML }}
        run: |
          mkdir -p config
          printf '%s\n' "$CONFIG_CONTENT" > config/config.yaml

      - name: 执行签到任务
        run: python main.py
      - name: 检查配置文件
        run: |
                ls -la config/
                cat config/config.yaml
